use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::fmt::Display;
use strum::{EnumDiscriminants, EnumIter};

pub const MAX_SEARCH_DESCRIPTION_LENGTH: usize = 20;

#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum UserChannel {
    Telegram,
    Discord,
}
impl Display for UserChannel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            UserChannel::Telegram => write!(f, "Telegram"),
            UserChannel::Discord => write!(f, "Discord"),
        }
    }
}

impl UserChannel {
    fn to_string(&self) -> &'static str {
        match self {
            UserChannel::Telegram => "Telegram",
            UserChannel::Discord => "Discord",
        }
    }
}

#[derive(PartialEq, Eq, PartialOrd, Ord, Clone, Serialize, Deserialize)]
pub struct UserId(pub UserChannel, pub String);

impl Display for UserId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}_{}", self.0.to_string(), self.1)
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RecentConversation {
    pub thoughts: String,
    pub history: Vec<HistoryEntry>,
}
impl RecentConversation {
    pub fn history(&self) -> Vec<HistoryEntry> {
        self.history.clone()
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum UserState {
    Idle {
        recent_conversation: Option<(RecentConversation, DateTime<Utc>)>,
    },
    CommitingToMemory {
        recent_conversation: RecentConversation,
    },
    AwaitingLLMDecision {
        is_timeout: bool,
        history: Vec<HistoryEntry>,
        current_input: LLMInput,
    },
    RunningInternalFunction {
        is_timeout: bool,
        recent_conversation: RecentConversation,
    },
    SendingMessage {
        is_timeout: bool,
        outcome: LLMResponse,
        recent_conversation: RecentConversation,
    },
    RunningTool {
        is_timeout: bool,
        recent_conversation: RecentConversation,
    },
}
impl Default for UserState {
    fn default() -> Self {
        UserState::Idle {
            recent_conversation: None,
        }
    }
}

#[derive(Clone, Default, Serialize, Deserialize)]
pub struct User {
    pub pending: Vec<String>,
    pub state: UserState,
    pub last_transition: DateTime<Utc>,
}

/// Represents the input to the LLM decision-making process
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum LLMInput {
    /// A message from the user
    UserMessage(String),
    /// Continuation after an internal function execution with the function result
    InternalFunctionResult(InternalFunctionResultData),
    /// Continuation after a tool execution with the tool result
    ToolResult(ToolResultData),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum MathOperation {
    Add(f32, f32),
    Sub(f32, f32),
    Mul(f32, f32),
    Div(f32, f32),
    Exp(f32, f32),
}
/// The universe of executable tools. `ToolKind` (generated by `EnumDiscriminants`) is the
/// fieldless companion used to iterate variants when building the advertised tool registry —
/// see `crate::tools`.
#[derive(Debug, Clone, Serialize, Deserialize, EnumDiscriminants)]
#[strum_discriminants(name(ToolKind))]
#[strum_discriminants(derive(EnumIter))]
#[strum_discriminants(vis(pub))]
pub enum ToolCall {
    GetWeather { location: String },
    MathCalculation { operations: Vec<MathOperation> },
    WebSearch { query: String },
    VisitUrl { url: String },
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FunctionCall {
    RecallShortTerm { reason: String },
    RecallLongTerm { search_term: String },
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum LLMDecisionType {
    IntermediateToolCall { tool_call: ToolCall },
    InternalFunctionCall { function_call: FunctionCall },
    MessageUser { response: String },
}

/// The native tool call exactly as the model emitted it (parsed by `parse_response_oaicompat`).
/// Preserved so the assistant turn can be re-rendered with its `tool_calls` in the next prompt,
/// and so the following `tool` result message can reference the matching `id`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NativeToolCall {
    pub id: String,
    pub name: String,
    /// Raw JSON arguments string, e.g. `{"city":"Paris"}`.
    pub arguments: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LLMResponse {
    /// The model's reasoning (`<think>` channel). Kept for logging/memory only — NOT replayed
    /// into the next prompt (Qwen3 guidance).
    pub thoughts: String,
    pub output: LLMDecisionType,
    /// Present iff `output` is a tool call — the native call to replay into history.
    #[serde(default)]
    pub tool_call: Option<NativeToolCall>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum HistoryEntry {
    Input(LLMInput),
    Output(LLMResponse),
}

impl HistoryEntry {
    pub fn format_simplified(&self) -> String {
        match self {
            HistoryEntry::Input(llm_input) => match llm_input {
                LLMInput::UserMessage(m) => format!("User:\n{m}"),
                LLMInput::InternalFunctionResult(InternalFunctionResultData {
                    simplified, ..
                })
                | LLMInput::ToolResult(ToolResultData { simplified, .. }) => {
                    format!("Assistant:\n{simplified}")
                }
            },
            HistoryEntry::Output(LLMResponse { output, .. }) => {
                let text = match output {
                    LLMDecisionType::MessageUser { response } => response.clone(),
                    LLMDecisionType::IntermediateToolCall { tool_call } => format!("{tool_call:?}"),
                    LLMDecisionType::InternalFunctionCall { function_call } => {
                        format!("{function_call:?}")
                    }
                };
                format!("Assistant:\n{text}")
            }
        }
    }
}

#[derive(Clone, Serialize)]
pub enum UserAction {
    ForceReset,
    NewMessage {
        msg: String,
        start_conversation: bool,
    },
    Timeout,
    CommitResult(Result<(), String>),
    LLMDecisionResult(Result<LLMResponse, String>),
    InternalFunctionResult(Result<InternalFunctionResultData, String>),
    MessageSent(Result<(), String>),
    ToolResult(Result<ToolResultData, String>),
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct InternalFunctionResultData {
    pub actual: String,
    pub simplified: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ToolResultData {
    pub actual: String,
    pub simplified: String,
}

impl std::fmt::Debug for UserAction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            UserAction::ForceReset => write!(f, "ForceReset"),
            UserAction::NewMessage { .. } => write!(f, "NewMessage"),
            UserAction::Timeout => write!(f, "Timeout"),
            UserAction::CommitResult(_) => write!(f, "CommitResult"),
            UserAction::LLMDecisionResult(_) => write!(f, "LLMDecisionResult"),
            UserAction::InternalFunctionResult(_) => write!(f, "InternalFunctionResult"),
            UserAction::MessageSent(_) => write!(f, "MessageSent"),
            UserAction::ToolResult(_) => write!(f, "ToolResult"),
        }
    }
}
